// import { CLOUDINARY_CLOUD_NAME, CLOUDINARY_UNSIGNED_PRESET, CLOUDINARY_API_KEY, CLOUDINARY_SIGNED_PRESET, CLOUDINARY_URL } from '@env';

const CLOUDINARY_CLOUD_NAME = 'dg46gpi4v';
const CLOUDINARY_API_KEY = '957849175418574';
const CLOUDINARY_API_SECRET = 'Sy9NA-Q2w5ZVTCzsAma3QkOtzu0';
const CLOUDINARY_URL = 'cloudinary://<your_api_key>:<your_api_secret>@dg46gpi4v';
const CLOUDINARY_SIGNED_PRESET = 'gcsapeqj';
const CLOUDINARY_UNSIGNED_PRESET = 'y7docsnz';

//  ! Expo deosn;t support env file ATM
// const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
// const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
// const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
// const CLOUDINARY_URL = process.env.CLOUDINARY_URL;
// const CLOUDINARY_SIGNED_PRESET = process.env.CLOUDINARY_SIGNED_PRESET;
// const CLOUDINARY_UNSIGNED_PRESET = process.env.CLOUDINARY_UNSIGNED_PRESET;
//  ! Expo deosn;t support env file ATM

export { CLOUDINARY_URL, CLOUDINARY_UNSIGNED_PRESET, CLOUDINARY_SIGNED_PRESET, CLOUDINARY_CLOUD_NAME }